### ISSUE TITLE
CLI tests expect a loop an input loop `MusicController#call` but doesn't test for it

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/ruby-music-library-cli#12]
```
 Music Library CLI allows a user to list songs
     Failure/Error: expect(music_libray_controller).to receive(:gets).at_least(:once).and_return("list songs", "exit")
       (#<MusicLibraryController:0x007ffcd3c25060>).gets(*(any args))
           expected: at least 2 times with any arguments
           received: 1 time with any arguments
```

If they don't loop in their `call` method and only ask for user input once the failure is vague and hard to debug. We should write a test that explicitly asks for an input gets loop within call - something like `it 'loops and asks for user input until they type in exit`.

**Comment by pletcher** [comment]
Closed in https://github.com/ruchiramani/ruby-music-library-cli/commit/f99e91491c6ab7b980f4586a0deb0eb16f654173
