### ISSUE TITLE
Ask a Question is having errors. 

### ISSUE THREAD

**Issue by hangloos** [learn-co-curriculum/ruby-music-library-cli#20]
When I pull up what questions I should be receiving, it only gives me the option of "all previous lessons." The toggle on and off for it does not work though. Any ideas? 

Thanks!

**Comment by AnnJohn** [comment]
hi @hangloos this should be resolved now. Also if you do see this problem again, can you actually file a bug report? If you hover over your profile pic in Learn, you'll see an option to report a bug from a dropdown menu. We use this space for issues related to the curriculum content so filing a bug report will be the best way to alert our product team.

Thanks!

**Comment by hangloos** [comment]
Will do! I saw that later and put one in too. Thanks!

On Mon, May 9, 2016 at 2:09 PM, AnnJohn notifications@github.com wrote:

> hi @hangloos https://github.com/hangloos this should be resolved now.
> Also if you do see this problem again, can you actually file a bug report?
> If you hover over your profile pic in Learn, you'll see an option to report
> a bug from a dropdown menu. We use this space for issues related to the
> curriculum content so filing a bug report will be the best way to alert our
> product team.
> 
> Thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/learn-co-curriculum/ruby-music-library-cli/issues/20#issuecomment-217942783

## 

Best,

Eric Loos
www.ericeloos.com
Email - ericloos00@gmail.com

**Comment by AnnJohn** [comment]
great, thanks!
