### ISSUE TITLE
tests don't pass on solution branch

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/ruby-music-library-cli#23]
Something is wrong with the order in which the songs come up and are giving false negatives.

**Comment by bhollan** [comment]
Another student suggested that if `sort` is added to the importer it fixes the problem.
https://learn.co/lessons/13201?batch_id=306&track_id=12615&question_id=29118

**Comment by aturkewi** [comment]
@cjbrock this seems to come up infrequently, but I think it can be solved by using sort when returning the songs. @pickledyamsman will leave more info on what his error is in a moment! I just wanted to make sure to tag you in here.

**Comment by pickledyamsman** [comment]
This seems to be related to #25 

These are the tests that don't resolve:

![screenshot from 2016-11-02 19-09-07](https://cloud.githubusercontent.com/assets/11581503/19950772/e62d7e46-a12f-11e6-8d14-22350d287c94.png)

changing:
`def files
    @files ||= Dir.glob("#{path}/*.mp3").collect{|f| f.gsub("#{path}/", "")}
  end`

to:
`def files
    @files ||= Dir.glob("#{path}/*.mp3").collect{|f| f.gsub("#{path}/", "")}.sort()
  end`

passes the tests.

This seems to happen when a student is using a local environment and not when they are using the IDE.
