### ISSUE TITLE
Code expected is not DRY-ing

### ISSUE THREAD

**Issue by mkang85** [learn-co-curriculum/ruby-music-library-cli#41]
Hello, 

Just noticed that we had to copy the sort code that was already implemented in the #list_songs method.  This seems to be a bit redundant if we already have a method that produces the listed number of songs. 

`def list_songs
    Song.all.sort {|x,y| x.name <=> y.name}.each_with_index {|val, index| puts "#{index + 1}. #{val.artist.name} - #{val.name} - #{val.genre.name}" }
  end`

`def play_song
    puts "Which song number would you like to play?"
    num = gets.strip.to_i - 1
    song = Song.all.sort {|x,y| x.name <=> y.name}[num]
    if song && num.between?(0, Song.all.length-1) 
      puts "Playing #{song.name} by #{song.artist.name}"
    end
  end`

I think that it would've made sense to invoke #list_songs, and then manipulate the produced numbered list instead of sorting the song list twice.  The wording of the specs also kind of leads you to believe that we had to invoke #list_songs any way.  

`describe "#play_song" do
    it "prompts the user to choose a song from the alphabetized list output by #list_songs" do
      allow(music_library_controller).to receive(:gets).and_return("Testing for #puts")

      expect($stdout).to receive(:puts).with("Which song number would you like to play?")

      allow($stdout).to receive(:puts)

      music_library_controller.play_song
    end`

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the input. You could absolutely implement the shared logic in a helper method to dry up your code.

As always thank you for contributing!
