### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by swarbrick85** [learn-co-curriculum/ruby-music-library-cli#49]
Over night my code had a bunch of random numbers inserted and 

<<<<<<<<<<<<<<<<<<<<<<<<<<<, HEAD  

inserted 

one of my three files was deleted

**Comment by sgharms** [comment]
This seems to suggest a "merge conflict." This means that your code, when it was checked out disagreed with what had been archived to your copy of the challenge. I believe this to be a technical error.

You can reach them at support@learn.co.

Our apologies, but this should be a _very rare_ occurrence.
