### ISSUE TITLE
Suggestions for improvement - Music Library CLI Lab

### ISSUE THREAD

**Issue by merecka** [learn-co-curriculum/ruby-music-library-cli#55]
Overall I felt that this lab was very good and challenging.  It definitely helped reinforce the OOP concepts.  However, I have a couple of suggestions that could improve it and bring it "all together" at the end.

1.  After the lab is built and the tests are passing, there is nothing on the Learn page describing about how to interact with the program via the CLI.  We spend all of this time building this program, we should be encouraged to play around with it at the end!  Something like "once your tests are passing, try executing your program by typing /bin/musiclibrary and enjoy the results of your work!"

2.  In order for the program to respond to commands typed in via the CLI, all of the lines using 'gets' need to be revised to 'gets.chomp'.  The lab suggests using 'gets' but it should really suggest 'gets.chomp' so that everything is working once it is built.

**Comment by lizbur10** [comment]
Thank you for spotting these issues and providing feedback. The materials have been updated to reflect your suggestions.

Thanks for contributing to the Flatiron School curriculum 💙
