### ISSUE TITLE
Discrepancy between readme & test

### ISSUE THREAD

**Issue by IgoVeyner** [learn-co-curriculum/ruby-music-library-cli#60]
Readme instructs for an optional path to  './db/mp3s/' (line 102)
Test asks for an optional path to './db/mp3s' (line 15, 010_music_library_controller_spec.rb)

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this issue and providing feedback. The materials have been to correct the mismatch.

Thanks for contributing to the Flatiron School curriculum 💙
