### ISSUE TITLE
Must create multiple sources of truth to pass tests for Artist#genres and Genres#artist 

### ISSUE THREAD

**Issue by eleetyson** [learn-co-curriculum/ruby-music-library-cli#61]
In order to pass the tests for Artist#genres and Genres#artist in artists_and_genres_spec.rb, we have to create multiple sources of truth -- instead of storing all new instances in the @@all array for the Song class.

Huge shoutout to Nick Lunn for helping me with this. Apologies if this isn't best practice for submitting an issue, I just want to ensure other students and technical coaches are aware.

**Comment by eleetyson** [comment]
I also noticed that the Music Importer class' #import method needs to be an instance method, not a class method as .import would suggest in the README

**Comment by Madeline-Stark** [comment]
I agree that this is an issue! We emphasize single source of truth to our students, so it's very confusing for them that these tests force them to create multiple sources of truth.

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this issue and providing feedback. The materials have been updated to implement a single source of truth.

Thanks for contributing to the Flatiron School curriculum 💙
